### ISSUE TITLE
Training a zero shot argument extraction model

### ISSUE THREAD

**Issue by AaronCCWong** [wilburOne/ZeroShotEvent#6]
Hi,

I am trying to train the zero shot argument extraction model to perform step 6. Where can I find the `aceEventStructure.train.ace.format.transfer.neg.arg.10.txt` and `aceEventStructure.test.ace.format.transfer.neg.arg.10.txt` files that are set as the default values for the train, dev and test arguments for `zero_shot_arg_final.py`?

**Comment by AHNQz** [comment]
Hi Aaron, did you find those files? I am trying to do the same thing but I couldn't find them either.
